from pathlib import Path
from typing import Dict, Any

import joblib


MODEL_PATH = Path("models/baseline_ticket_type_classifier.joblib")


class TicketCategoryPredictor:
    """
    Loads the baseline ticket type classifier and returns predictions.

    Important:
    This model is retained as a baseline experiment only.
    Initial evaluation showed near-random performance due to noisy labels
    in the source dataset.
    """

    def __init__(self, model_path: Path = MODEL_PATH):
        self.model_path = model_path
        self.model = self._load_model()

    def _load_model(self):
        if not self.model_path.exists():
            raise FileNotFoundError(
                f"Model file not found at {self.model_path}. "
                "Run notebooks/02_ticket_classification_model.ipynb first."
            )

        return joblib.load(self.model_path)

    def predict(self, ticket_text: str) -> Dict[str, Any]:
        if not ticket_text or not ticket_text.strip():
            raise ValueError("ticket_text cannot be empty.")

        prediction = self.model.predict([ticket_text])[0]

        result = {
            "predicted_ticket_type": prediction,
            "model_status": "baseline_only",
            "note": (
                "This prediction is generated by a baseline classifier. "
                "Model performance is limited because the source dataset contains noisy labels."
            ),
        }

        if hasattr(self.model, "predict_proba"):
            probabilities = self.model.predict_proba([ticket_text])[0]
            classes = self.model.classes_

            confidence_scores = {
                class_name: round(float(prob), 4)
                for class_name, prob in zip(classes, probabilities)
            }

            result["confidence_scores"] = confidence_scores
            result["top_confidence"] = round(float(max(probabilities)), 4)

        return result


if __name__ == "__main__":
    predictor = TicketCategoryPredictor()

    sample_ticket = "I cannot access my account and password reset is not working."

    prediction = predictor.predict(sample_ticket)

    print(prediction)